version: 2

node_8: &node_8
  docker:
    - image: node:8@sha256:7ed12d4810ed02b8c908d554976062ae61f42db8252bb9e148da0bffb72fb086

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test

jobs:
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  deliver:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies_deliver
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: v1-dependencies_deliver
      - run: $(yarn bin)/semantic-release-github --preset @hbetts/config
  deploy:
    <<: [*node_8]
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies_deploy
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ${HOME}/.cache/yarn
          key: v1-dependencies_deploy
      - run: $(yarn bin)/npm-publish-git-tag --access public

workflows:
  version: 2
  build:
    jobs:
      - node_8_test_plan
      - deliver:
          filters:
            branches:
              only: master
          requires:
            - node_8_test_plan
          context: github-interaction
      - deploy:
          filters:
            tags:
              only: /.+/
          requires:
            - deliver
          context: npm-interaction
