version: 2.1

orbs:
  release-workflows: hutson/library-release-workflows@4.3.3

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test

jobs:
  node_8_test_plan:
    <<: [*test_plan]
    docker:
      - image: node:8@sha256:7898114f45abe72c66313af8ee713dd48a6993fbaa71502e3341546117cff170

workflows:
  version: 2

  build_and_test:
    jobs:
      - node_8_test_plan
      - release-workflows/deliver:
          context: github-interaction
          filters:
            branches:
              only: master
          requires:
            - node_8_test_plan

  deploy:
    jobs:
      - release-workflows/npm-deploy:
          access: public
          context: package-publishing
          filters:
            tags:
              # Match only semantically valid semver tags - Authored by David Fichtmueller - https://github.com/semver/semver/issues/232#issue-48635632
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
